version: '2.1'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - servers
    depends_on:
      - server1
      - server2
      - server3
      - balancer

  balancer:
    # Для тестів включаємо режим відлагодження, коли балансувальник додає інформацію, кому було відправлено запит.
    command: ["lb", "--trace=true"]
